name: Lint and Test
permissions:
  contents: read
on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  lint-test-and-build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update -y && sudo apt install -y gcc-x86-64-linux-gnu gcc-aarch64-linux-gnu gcc-mingw-w64-x86-64
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x
      - run: task deps
      - run: task lint
      - run: task test
      - run: task test:e2e:tun
      - run: task test:e2e:lib:tun
      - run: task build
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: build/
          if-no-files-found: error
          retention-days: 7

  build-lib-darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x
      - run: task deps

      - run: task build:lib:darwin
      - uses: actions/upload-artifact@v4
        with:
          name: darwin-${{ github.sha }}
          path: build/
          if-no-files-found: error
          retention-days: 7

  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: [lint-test-and-build, build-lib-darwin]
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: ${{ github.sha }}
          path: build
      - uses: actions/download-artifact@v6
        with:
          name: darwin-${{ github.sha }}
          path: build
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            build/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
